services:
    postgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: mstore-api
            POSTGRES_USER: marko-
            POSTGRES_PASSWORD: markoadmin
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4
      ports:
        - 5050:80
      environment:
        PGADMIN_DEFAULT_EMAIL: markoadmin@mail.com
        PGADMIN_DEFAULT_PASSWORD: markoadmin



